### ISSUE TITLE
How many epoches should the model be trained?

### ISSUE THREAD

**Issue by PhyllisH** [fengyang0317/video_reloc#3]
About 1000 epoches, the model has the performance.
map@1    0.5     0.6    0.7    0.8    0.9    average
                35.4    30.0  21.1  12.6  5.0    20.7
in paper   43.5    35.1  27.3  16.2  6.5   25.7
There are obvious gaps between the trained result and the reported.

**Comment by fengyang0317** [comment]
![image](https://user-images.githubusercontent.com/7965501/47207860-f1df7280-d3be-11e8-977c-26c735a2eb76.png)

In fact, the best checkpoint was obtained within 1000 iterations. Please look at the IoU/mean in Tensorboard. Use the checkpoint with the highest validation IoU. For example, I use model.ckpt-200 for the above figure.

**Comment by PhyllisH** [comment]
Thanks. After checked the tensorboard, I got the following performance.
map@1 0.5 0.6 0.7 0.8 0.9 average
             42.0 34.6 24.6 14.7 5.5 24.3
in paper 43.5 35.1 27.3 16.2 6.5 25.7
Is this gap in the tolerant range?

**Comment by fengyang0317** [comment]
Thanks for your interest in our paper. I think the difference may be caused by the initialization. You may try different initializations.

Using the code in this repository, the best results I got are a little higher. You can download the checkpoints at https://drive.google.com/file/d/1AisOmAxRHJMSZFuPBiWU_sxsY72d0YO4/view?usp=sharing

**Comment by PhyllisH** [comment]
Thanks for your patience~
